### ISSUE TITLE
Using dynamic values as Relay query variables

### ISSUE THREAD

**Issue by lukehedger** [4Catalyzer/found-relay#100]
This is more of a question about effective paradigms when working with **Relay Modern** via `found-relay` than an issue but I feel there could be a better pattern for passing dynamic values to Relay queries.

I've come across two scenarios where I need to set Relay query variables to dynamic values:
1. URL path or querystring parameters - eg. `/myroute/:id` or `/myroute?id=xyz`
2. Application state - eg. Redux store

At the moment I achieve this like so:

```
<Route
  path='/path-one/:id'
  Component={SomeComponent}
  query={someQuery}
  prepareVariables={params => ({
    ...params,
    id: `${reduxStore.getState().id}`,
  })}
/>

<Route
  path='/path-two/:id'
  Component={SomeComponent}
  query={someQuery}
  prepareVariables={params => ({
    ...params,
    id: window.location.pathname.split('/')[3],
  })}
/>
```

But I feel this is fairly crude, so I am wondering if anyone has devised a cleaner pattern?

**Comment by taion** [comment]
For the latter example (case 1), you can see that `params` by default includes all the route params, so you don't need the `prepareVariables` there: https://github.com/4Catalyzer/found-relay/blob/ceb1195a9cf1eb25806a2b44c26454d853714f89/test/modern/Resolver.test.js#L101-L125

For the former example (case 2), what you have looks about right to me.

**Comment by lukehedger** [comment]
Ah nice tip for the route params - thanks @taion, had not spotted that!

As for the Redux case, this will do for now then. The only complication could be if the state variable has not been set when the route is requested but this can be handled at component level with a programmatic redirect if needed.

**Comment by taion** [comment]
BTW you should use match.context for the Redux store instead of a global anyway, if you want to be SSR friendly. But yeah I can’t think of anything better in that case.

**Comment by lukehedger** [comment]
Excellent - this is much cleaner. Will give it a go.

**Comment by MartinDawson** [comment]
For anyone else wondering where `context` is, it's passed in as a property on the second parameter of `prepareVariables`.

**Comment by earksiinni** [comment]
Just to be super clear, when using Found with client side rendering, I believe that @MartinDawson's comment holds by default, in that you can access the store through the second parameter passed into `prepareVariables`, like this: `secondParameter.context.store`. That is, the store is included in the context. This may also hold true under a number of SSR scenarios.

However, if you're using a custom Redux store during SSR, and specifically if you're generating a set of `renderArgs` that you pass into the router, you will need to include the store inside of your `matchContext`. My code looks something like this:

```
import getStoreRenderArgs from 'found/lib/getStoreRenderArgs';
// other relevant imports
...

// createStoreWithProtocol is a function that I wrote to create a Redux store...
// your implementation will look different, but the returned value should be a store
const store = createStoreWithProtocol(new ServerProtocol(location), preloadedState);
const renderArgs = await getStoreRenderArgs({
  matchContext: { store },
  resolver,
  store,
});
const renderRoutes = createRender({});
const Router = () =>
  React.createElement(RouterProvider, {
    children: renderRoutes(renderArgs),
    renderArgs,
  });

// Root is my app container
// I use Router as my Router component and pass store to Redux's Provider
const renderedReact = ReactDOMServer.renderToString(
  React.createElement(Root, { Router, store })
);
```

**Comment by taion** [comment]
@earksiinni In both cases, you need to pass the Redux store into the `matchContext`, no? There's not really any other way to get access to it. So it's more or less the same in both cases?

**Comment by earksiinni** [comment]
@taion quite right! I just updated my comment above, I wasn't familiar with using `matchContext` before.

In my case, I had to add the store to three places: `matchContext` during SSR, `matchContext` on the client side as a prop on my `BrowserRouter`, and `matchContext` as a property of the object passed into the `initialRenderArgs` prop on my `BrowserRouter`.

**Comment by taion** [comment]
Wait, hold on – are you not using `createInitialBrowserRouter` or `createInitialFarceRouter` per https://github.com/relay-tools/found-relay/blob/153b45d86fe5b415139d6440eca003f435769ccd/examples/todomvc-universal/src/client.js#L22-L32 ?

**Comment by taion** [comment]
i.e. for the client side, when doing SSR, you should be using one of the `createInitialFooRouter` functions

**Comment by earksiinni** [comment]
@taion, the code that I pasted above is from the server side. On the client side, I'm using `createConnectedRouter` with a custom store. Everything seems to work fine, except for the fact that it renders twice upon load, once with `initialRenderArgs` and the second time with whatever I passed into the `matchContext` prop. Not sure whether that's avoidable or not.

[The docs here](https://github.com/4Catalyzer/found#server-side-rendering-with-custom-redux-store) state:

> Found exposes lower-level functionality for doing server-side rendering for use with your own Redux store, as with createConnectedRouter above...On the client, pass the value resolved by by getStoreRenderArgs to your <ConnectedRouter> as the initialRenderArgs prop.

My client side code looks like:

```js
// Set up Redux store
const preloadedState = window.__PRELOADED_STATE__;

// Allow the passed state to be garbage-collected
delete window.__PRELOADED_STATE__;

const store = createStoreWithProtocol(new BrowserProtocol(), preloadedState);

// Set up Relay
const relayClientSSR = new RelayClientSSR(window.__RELAY_BOOTSTRAP_DATA__);
const network = new RelayNetworkLayer([
  relayClientSSR.getMiddleware({
    // Will preserve cache rather than purge after mount.
    lookup: false,
  }),
  urlMiddleware({
    credentials: 'include',
    headers: {
      Accept: 'application/json',
    },
  }),
]);

// Set up Found router
const ConnectedRouter = createConnectedRouter({ render: renderRoutes });
const resolver = new Resolver(
  createEnvironment({
    network,
  })
);
const initialRenderArgs = await getStoreRenderArgs({
  resolver,
  store,
});
const renderRoutes = createRender({});
const Router = () => (
  <ConnectedRouter initialRenderArgs={initialRenderArgs} resolver={resolver} />
);

hydrate(<Root Router={Router} store={store} />, document.getElementById('app'));
```

**Comment by taion** [comment]
Hmm, I'm not totally sure about the second render. I don't expect that to happen, but I haven't looked at it in detail recently. Your code doesn't show passing `matchContext` into `<ConnectedRouter>`, but from your description, I assume you're doing it.

For reference, here are the bundled examples for SSR with a custom Redux store:
https://github.com/4Catalyzer/found/blob/6149b46fa29aee08e2a738609590bbbad00c32a3/examples/universal-redux/src/server.js#L63-L94
https://github.com/4Catalyzer/found/blob/6149b46fa29aee08e2a738609590bbbad00c32a3/examples/universal-redux/src/client.js#L19-L36

And they in fact match what you described.
