### ISSUE TITLE
Redirecting doesn't trigger query call

### ISSUE THREAD

**Issue by MartinDawson** [4Catalyzer/found-relay#101]
```
const query = graphql`
  query socialLoginCallbackContainerQuery {
    externalLoginCallback {
      loginProvider,
      newUserName
      user {
        userName
      }
    }
  }
`;
```

```
const render = (route) => {
  if (route.props) {
    // User already has an account that is logged in so redirect them
    if (route.props.externalLoginCallback.existingUser) {
      route.props.context.store.dispatch(showLoginPopup());

      throw new RedirectException('/');
    } else {
      // associate the users account
      return (
        <SocialLoginConfrimationContainer
          newUserName={route.props.externalLoginCallback.newUserName}
          loginProvider={route.props.externalLoginCallback.loginProvider}
          returnUrl={route.props.params.returnUrl}
        />
      );
    }
  }

  return null;
};
```

I am using OAUTH twitter login on server side to log the user in, if they have already got an account associated my website then I want to redirect them back to the homepage. On the homepage I run a query to get the users username to show it on the screen. The problem is when I redirect the user using `throw new RedirectException('/');` the query on the home route that gets the username doesn't get run again so the username never updates.

If I do this instead:

    // User already has an account that is logged in so redirect them
    if (route.props.externalLoginCallback.user) {
      route.props.context.store.dispatch(showLoginPopup());

      window.location.href = "/";
    }

Then that will work and run the query again but it produces a full page refresh obviously. How do I use found's routing system to redirect to another route and also update the userName with the new values or re-run the root query?

Root query: 

```
const query = graphql`
  query appContainerQuery {
    user {
      userName
    }
  }
`;
```

**Comment by taion** [comment]
See https://github.com/4Catalyzer/found-relay/pull/32. This is sort of matching the `<QueryRenderer>` behavior of not refetching unchanged queries.

The thing is, in your case, most of the time, you don't want to refetch that query, right? Consider using `location.state` to set up the variables to force a change.

**Comment by MartinDawson** [comment]
@taion Thanks for the quick reply, I'll check it out. Why wouldn't I want to refetch the query though?

**Comment by taion** [comment]
Well, normally you'll have already fetched it, so it'd just be an extra query for no real benefit, since the results usually don't change.

**Comment by MartinDawson** [comment]
I tried this:

```
if (route.props.externalLoginCallback.user) {
  route.props.context.store.dispatch(showLoginPopup());
  route.props.location.state = route.props.externalLoginCallback.user;

  throw new RedirectException'/');
}
```

And then in my root query:

```

const query = graphql`
  query appContainerQuery{
    user {
      userName
    }
  }
`;

const PrimaryLayoutContainer = PrimaryLayout;

export const routeConfig = {
  Component: PrimaryLayoutContainer,
  query,
  render: (route) => {
    if (route.props) {
      if (!route.user) {
        route.user = route.props.location.state.user;
      }
    }
    return route.props && <PrimaryLayoutContainer {...route.props} />;
  },
};

export default AppContainer;
```

State doesn't exist on the root app render though,

**Comment by taion** [comment]
You want to do something like:

```js
throw new RedirectException({
  pathname: '/',
  state: { /* whatever */ },
});
```

then you can just access it as `location.state`.

**Comment by MartinDawson** [comment]
I get this error when trying that:

`Uncaught Error: React.Children.only expected to receive a single React element child.
    at invariant (invariant.js:42)
    at Object.onlyChild [as only] (onlyChild.js:31)
    at StaticContainer.render (StaticContainer.react.js:63)
    at finishClassComponent (react-dom.development.js:7902)
    at updateClassComponent (react-dom.development.js:7879)
    at beginWork (react-dom.development.js:8253)
    at performUnitOfWork (react-dom.development.js:10244)
    at workLoop (react-dom.development.js:10308)
    at HTMLUnknownElement.callCallback (react-dom.development.js:540)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:579)`

App.jsx:

```
<ErrorBoundary>
    <Provider store={store}>
      <div>
        <Router matchContext={{ store }} resolver={resolver} />
      </div>
    </Provider>
</ErrorBoundary>
```

I also tried just having one child in routeConfig:

```
<Route path="/" {..appRouteConfig}>
    <Route {...songsRouteConfig} />
</Route>,
```

But I still get this error.

**Comment by taion** [comment]
What are you returning from the `render` callback you pass into `create(Whatever)Router`?

Schematically, what you want is something like this:

```js
const loginRoute = {
  /* ... */

  query: graphql`
    query LoginQuery {
      userName
      # ...
    }
  `,

  render: ({ props }) => {
    if (props && props.userName) {
      throw new RedirectException({
        pathname: '/',
        state: { loggedInUsername: username },
      });
    }

    /* ... */
  },
};

const appRoute = {
  /* ... */

  prepareVariables: (variables, { location }) => ({
    ...variables,
    // For cache invalidation.
    __loggedInUsername: location.state && location.state.loggedInUsername,
  }),
};
```

In other words, suppose something changes such that you want to re-run the root query based on some query results in a child route – trigger the redirect, then add a dummy variable in the root route that has a new value, which will trigger the cache invalidation.
