### ISSUE TITLE
How do we test routes and queries?

### ISSUE THREAD

**Issue by MartinDawson** [4Catalyzer/found-relay#102]
I want to add tests, either unit or integration but I have no idea how or how to mock graphql.

Let's say I wanted to test the following component that is on a `<Route path='confirmEmail' {...routeConfig} />` how would I do it? Would you mock anything out?

Thanks alot.

```
const query = graphql`
  query confirmEmailContainerQuery(
    $userId: String!
    $token: String!
  ) {
    confirmEmail(userId: $userId, token: $token)
  }
`;

const render = (route) => {
  if (route.props) {
    route.props.context.store.dispatch(showEmailConfirmationPopup());

    throw new RedirectException('/');
  }

  return null;
};

export const routeConfig = {
  query,
  prepareVariables: ({ userId, token }) => ({ userId, token }),
  render,
};

```

**Comment by taion** [comment]
If you want to test routing, use the Found SSR API. 

For testing query handling, do whatever you would with Relay normally. Probably just mock the network responses by using a test dummy for the network layer.
