### ISSUE TITLE
my app doesn't get render when using django backend

### ISSUE THREAD

**Issue by mrabedini** [4Catalyzer/found-relay#103]
I have created my app with create-react-app, I don't have any problem when I use `yarn start`. It works like a charm in that case. 
However, when I run `yarn build` and serve the index.html and created main.*.js with django. My app doesn't get rendered and my page look like the following:

```
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
	<meta name="theme-color" content="#000000">
	<link rel="manifest" href="/en/panel/tracking/manifest.json">
	<link rel="shortcut icon" href="/en/panel/tracking/favicon.ico">
	<title>React App</title>
</head>

<body><noscript>You need to enable JavaScript to run this app.</noscript>
	<div id="root"></div>
	<script type="text/javascript" src="/static/js/main.cc34c8c5.js"></script>
</body>

</html>
```
I also have sent all urls to my index.html with * in urls.py . 
I see the same result when opening index.html in my build folder.
what should I do to trigger the rendering?

**Comment by taion** [comment]
I don't think this issue has anything to do with Found Relay.

**Comment by mrabedini** [comment]
@taion Yes you were right. For audience who might encounter the same problem:
My mistake was that I setup my routing with "/" but I was serving it in "/en/panel/tracking/". Routing config and serving must match with each other. 
A silly mistake!😅
