### ISSUE TITLE
App breaks when upgrading from alpha6 to alpha9

### ISSUE THREAD

**Issue by alexhawkins** [4Catalyzer/found-relay#104]
I recently upgraded our app ( https://www2.onehopewine.com/shop/wine/wine ) from alpha6 to alpha9 and things stopped working. Specifically when navigating to routes that use prepareParams with refetchContainers. Basic/less complex routes seem to be ok. Is there anything that you can think of that was changed in alpha9 that would cause this sort of drastic behavior? This app was originally a relay classic app that we've slowly upgraded to modern over time.  We've been on alpha6 in production for several months now with no issues. There could also be some legacy stuff in our app that finally broke with the alpha9 upgrade. Not sure. Any ideas on what might be going on would be much appreciated :) Thanks.

**Comment by taion** [comment]
Two possibilities:
- Did you upgrade to Relay v1.4.0? (https://github.com/4Catalyzer/found-relay/pull/88)
- Were you using `prerender` or returning `undefined` from render? (https://github.com/4Catalyzer/found-relay/releases/tag/v0.3.0-alpha.7)

**Comment by taion** [comment]
Any update here?

**Comment by johntran** [comment]
We're not using prerender and we did upgrade to Relay 1.4.0.

I'll have better updates on Friday :). I'll let you know what errors are happening and what steps I took then.

**Comment by taion** [comment]
It'd be helpful if you could also tell me which release broke things. The riskiest change might be https://github.com/4Catalyzer/found-relay/pull/91, which landed in alpha 8, but it works for basic cases, at least, and doesn't obviously seem to affect refetch things.

**Comment by johntran** [comment]
alpha 7 was the one that broke the build

``` warning.js:33 Warning: RelayModernSelector: Expected object to contain data for fragment `ProductsCatalog_viewer`, got `{"isLoggedIn":true,"canEdit":false,"user":{"id":"VXNlcjpxb3ljaWVtYXNrbGZoa2Vs","publicId":"87b613eb-4ae8-4167-a0f8-a69b415a27c8","role":"user","email":"j@gmail.com","cart":{"id":"Q2FydDo=","totalNumberOfItems":1}},"__fragments":{"HomePage_viewer":{},"Checkout_viewer":{},"NavbarComponent_viewer":{},"ShopLeftNavComponent_viewer":{},"CartRightNavComponent_viewer":{},"ProductDetailsPage_viewer":{}},"__id":"client:root:viewer"}`. Make sure that the parent operation/fragment included fragment `...ProductsCatalog_viewer` without `@relay(mask: false)`. ```

It is sending this network call

```
"query ProductCatalog_Query(
  $count: Int
  $category: String
  $sortBy: String
  $filterPrice: [String]
  $filterByCause: [String]
  $filterByType: [String]
  $filterByVarietal: [String]
  $filterByGiftCategories: [String]
  $productCategories: [String]
  $productsExclude: [String]
  $productsOnly: [String]
) {
  viewer {
    ...ProductsCatalog_viewer_4muyEu
  }
}

fragment ProductsCatalog_viewer_4muyEu on Viewer {
  user {
    ...AuthDialog_user
# really long query
```
So it seems like the name of the fragment sent doesn't match with what is expected.

`ProductsCatalog_viewer` vs ` ProductsCatalog_viewer_4muyEu`

Route
```
  <Route
      path="shop/sale/:category"
      getQuery={() => require('../queries/ProductCatalog').default}
      getComponent={lazyLoadProductCatalog}
      prepareVariables={prepareProductCatalogParams}
      render={renderComponent}
    />
```

/queries/ProductCatalog

```
import { graphql } from 'graphql-relay';

export default graphql`
  query ProductCatalog_Query(
    $count: Int
    $category: String
    $sortBy: String
    $filterPrice: [String]
    $filterByCause: [String]
    $filterByType: [String]
    $filterByVarietal: [String]
    $filterByGiftCategories: [String]
    $productCategories: [String]
    $productsExclude: [String]
    $productsOnly: [String]
  ) {
    viewer {
      ...ProductsCatalog_viewer
        @arguments(
          count: $count
          category: $category
          sortBy: $sortBy
          filterPrice: $filterPrice
          filterByCause: $filterByCause
          filterByType: $filterByType
          filterByVarietal: $filterByVarietal
          filterByGiftCategories: $filterByGiftCategories
          productCategories: $productCategories
          productsExclude: $productsExclude
          productsOnly: $productsOnly
        )
    }
  }
`;
```
helper functions
```
export const lazyLoadProductCatalog = () =>
  System.import(
    '../components/Layouts/ProductPage/ProductsCatalog/ProductsCatalog',
  ).then(module => module.default);
export const prepareProductCatalogParams = (params, { location }) => {
  const { state } = location;
  if (state) {
    const {
      count,
      sortBy,
      category,
      filterPrice,
      filterByGiftCategories,
      filterByCause,
      filterByVarietal,
      filterByType,
    } = state;
    const customParams = prepareCustomParams({ category });
    const { productsExclude, productsOnly, productCategories } = customParams;
    return {
      ...params,
      count: count || SIZE_PER_PAGE,
      sortBy,
      category,
      filterPrice,
      filterByGiftCategories,
      filterByCause,
      filterByVarietal,
      filterByType,
      productCategories,
      productsExclude,
      productsOnly,
    };
  }
  return {
    ...params,
  };
};

export const renderComponent = args => {
  const { Component, props } = args;
  if (!Component || !props) {
    return <Loading />;
  }
  return <Component {...props} />;
};
```

**Comment by taion** [comment]
I don't think that's quite right. I believe Relay always generates a hash when using `@arguments`, so this should have been the same before any of the upgrades. In fact the link you have above (which I believe works?) is in fact using `...ProductsCatalog_viewer_4muyEu`.

Can you verify that this doesn't happen with alpha.6 against Relay v1.4.x? I'm looking through the alpha.7 changes, and none of them seem to affect query fetching. They only affect rendering.

Is this happening on the initial render, on refetches, or both?

**Comment by johntran** [comment]
We are running Relay 1.4.0 with alpha.6.

This happens on initial render.

What is actually happening is that our parent route has a query, and all of their Relay data is sent to the children.
```
  <Route path="/" query={AppQuery} Component={AppComponent}>
    <Route
      getQuery={() => require('../queries/HomePage').default}
      getComponent={lazyLoadHomePage}
      render={renderComponent}
    />
    <Route
      path="shop/:category"
      getQuery={() => require('../queries/ProductCatalog').default}
      getComponent={lazyLoadProductCatalog}
      prepareVariables={prepareProductCatalogParams}
      render={renderComponent}
    />
.....
````

All Relay data such as the `viewer` data and `__fragments` meant for `AppComponent` is sent to the React component related to `shop/:category`.

There is only one page on the site where it doesn't do that. 

I'm not sure what to do to go forward.

**Comment by johntran** [comment]
AppComponentProps:
![appcomponentprops](https://user-images.githubusercontent.com/3813391/33914160-c17effa0-df51-11e7-8be6-3a4095fa756b.png)

ProductCatalogProps:
![productcatalogprops](https://user-images.githubusercontent.com/3813391/33914164-c6bf41d2-df51-11e7-8e4a-0244defbc80e.png)

Expected props: 
![expectedprops](https://user-images.githubusercontent.com/3813391/33914168-cd17d0a8-df51-11e7-8e17-4adb6a74c25b.png)

**Comment by taion** [comment]
Okay, yes, that parent prop thing would do it. So the parent route passes Relay props down to the child route via like React.cloneElement?

**Comment by taion** [comment]
Oh, I misread. I have some suspicions. Will check shortly.

**Comment by taion** [comment]
Actually, can you confirm if you're using `React.cloneElement` to render `children` from the parent route here?

There was something wonky with the relative ordering of Relay props:
- Old: https://github.com/4Catalyzer/found-relay/pull/45/files#diff-f924379da264bc656de49c7ec8ca8463L100
- New: https://github.com/4Catalyzer/found-relay/pull/45/files#diff-f924379da264bc656de49c7ec8ca8463R94

i.e. in the current version of the code, `ownProps` takes precedence over `props`.

The old behavior was sort of weird for a variety of reasons. The change wasn't entirely intentional, but the old behavior was a little weird too.

**Comment by taion** [comment]
Okay, that's exactly it. You're passing in `viewer` as a prop into `<Main>` from `<AppComponent>`, then using `cloneElement` with all of `this.props` to inject it into the child, which in this case is the child route.

As far as I can tell, you're not using `viewer` there... as for what we should do here, I suppose we should drop everything from `ownProps` that collides with a key in `querySubscription.readyState.props` (and warn in dev mode)... like I think that code is a little weird, but it shouldn't break like this.

**Comment by taion** [comment]
I have a fix up on https://github.com/4Catalyzer/found-relay/pull/106. Could you test it and let me know if it works? You will now see a warning (in development only) for the shadowing `viewer` prop, because the semantics of the initial render are technically a bit different now, but it should mostly work as you expect.
