### ISSUE TITLE
Stop query being executed until parameter exists

### ISSUE THREAD

**Issue by MartinDawson** [4Catalyzer/found-relay#108]
RouteConfig:

  ```js
<Route path="/" {...primaryLayoutRouteConfig}>
    <Route {...editSongModalRouteConfig} />
    <Route {...songsRouteConfig} />
  </Route>
```

```js
const fragments = graphql`
  fragment editSongModalContainer_song on Song {
    name
    coverImageUrl
    artist
  }
`;

const query = graphql`
  query editSongModalContainerQuery(
    $songId: Int!
  ) {
    song(id: $songId) {
      ...editSongModalContainer_song
    }
  }
`;

export const routeConfig = {
  Component: EditSongModalContainer,
  query,
  prepareVariables: (_, { location }) => ({
    songId: location.state && location.state.modalId,
  }),
};
```

The editSong is a modal popup. I am using state to pass the modalId and not path because I don't want it to show in the url.
The problem is that query gets executed instantly when the modalId hasn't been passed yet. I pass the modalId when the user clicks on an icon.
How do I stop the query being executed unless modalId exists?

**Comment by taion** [comment]
You could use `getQuery` to check `location.state` and `location.state.modalId`, and return some other query if `modalId` isn't present.

What's your route supposed to render in that case?

**Comment by MartinDawson** [comment]
@taion Ah, great. Didn't know about `getQuery`. The route should just render nothing if `modalId` is not present.

**Comment by taion** [comment]
Yup, just return `null`. It will disable the Relay stuff, so just return `null` in `render` (or have `getComponent` return `null`).
