### ISSUE TITLE
Not working with relay v1.5.0-rc.1

### ISSUE THREAD

**Issue by crohlfs** [4Catalyzer/found-relay#112]
It looks like in the upcoming release of relay `getOperation` from `environment.unstable_internal` has been renamed to `getRequest` in this commit https://github.com/facebook/relay/commit/022b7e1232dd485643cfedfd38388f82d3755205.

This affects Resolver.js:
https://github.com/4Catalyzer/found-relay/blob/5ef5ec500f3d227b6165769f496f46699d160394/src/modern/Resolver.js#L103

If you'd like I can make a pull request handling either function existing.

**Comment by taion** [comment]
That sounds great. Could you also add a FIXME to remove the deprecated form at some point in the future?
