### ISSUE TITLE
Support Relay 2

### ISSUE THREAD

**Issue by metacortex** [4Catalyzer/found-relay#12]
Hi.

Any plan to support Relay Modern?

I am big fan of `found`,
and looking forward to use the new relay with it.

**Comment by taion** [comment]
Yeah, will update when I get a chance to wrap my mind around it all

**Comment by colepatrickturner** [comment]
Found is my favorite router and I looked into swapping out Relay classic with rudimentary modern support, and one of the bottlenecks I ran into is that Pagination and Refetch containers do not expose the query that is used when creating the component for those containers.

**Comment by taion** [comment]
See https://github.com/facebook/relay/issues/1687.

I'm not really planning to touch the pagination or refetch containers; instead my current plan is to have each route for Relay 2 act like a `<QueryRenderer>`, the way routes currently act like `<Relay.Renderer>`s.

**Comment by colepatrickturner** [comment]
Looking forward to seeing how it will work. Thanks again @taion!

I am currently upgrading an app to Modern Relay and intend to continue using Found, which is why I have forked `found-relay` have a crude working implementation with Modern Relay:

https://github.com/colepatrickturner/found-relay/commit/f0352653f0a2d71f495ada2f3adb9aadd9581b0b

```  <Route
    Component={Container}
    initialVariables={{
      ...
    }}
    query={query}
  />```

Where `initialVariables` can be either an object or `function(route)` and `query` is a GraphQL template literal.

**Comment by taion** [comment]
@colepatrickturner 

That's not quite optimal – since you're nesting `<QueryRenderer>`s, you'll end up firing off your queries serially.

I need to do an upstream change in Found to how element resolvers work to properly support concepts like leaving routes, in order to enable the proper GC behavior.

**Comment by rosskevin** [comment]
I'm doing a big change, converting to `found`, `found-relay`, and moving everything to `relay@1.0` (modern).  I see that #17 was just merged.  What is the status on relay 1.0 support, and is there anything I can do to help?

**Comment by taion** [comment]
@rosskevin 

If you just want to use `react-relay/classic`, see https://github.com/4Catalyzer/found-relay/tree/relay-1.

I'm going to merge that soon, but need to figure out release plans. I might cut a v0.2.x that supports a few minor Found API changes (https://github.com/4Catalyzer/found-relay/tree/relay-1) but still uses Relay v0.10.x, then cut a v0.3.x that supports Relay v1.x.

If you actually want to use the modern API with `<QueryRenderer>`, then I'm still a few days away from having something that works.

**Comment by rosskevin** [comment]
Thanks @taion - I'm looking to use the `QueryRenderer` version.  Please ping me if I can help out.

**Comment by taion** [comment]
Nope, I should have something up in a few days.

**Comment by taion** [comment]
Thanks though!

**Comment by rosskevin** [comment]
@taion Thank you!  

I'm working on converting and getting all the code ready in the meantime (including a flow type libdef for `found`).  It seems like the `relay-compiler` step for persisted queries e.g. `relay-compiler --src ./src --schema ./schema.json` may be at odds with the approach of putting a root query on a route.  All of my relay-compiler errors are related to such root queries.  Arguably, I'm a graphql novice so I may be missing something simple.

I'll be interested to see your approach in a todo modern example.

**Comment by taion** [comment]
@rosskevin What error specifically are you seeing?

**Comment by rosskevin** [comment]
All on the root queries, relative to `relay-todomvc` we have one just like it:

```js
import {graphql} from 'react-relay/compat'

export default {
  viewer: () => graphql`query ViewerQueriesQuery { viewer }`
}
```
The error will be:

```
Error: You supplied a GraphQL document with validation errors:
Field "viewer" of type "Viewer" must have a selection of subfields. Did you mean "viewer { ... }"?
```

**Comment by taion** [comment]
See https://github.com/4Catalyzer/found-relay/pull/27. https://github.com/4Catalyzer/found-relay/blob/relay-modern/test/modern/Resolver.test.js specifically demonstrates how to set up queries with Relay Modern.

**Comment by taion** [comment]
Released as v0.3.0-alpha.1. See https://github.com/taion/relay-todomvc/tree/found-modern for an example.

**Comment by taion** [comment]
Note BTW there's no `found-relay/lib/compat` – at least, not yet. We're only just starting the move to Relay v1.x in our code base, so it hasn't come up yet. At the moment I'm not sure if it will.

**Comment by colepatrickturner** [comment]
Thank you @taion!

**Comment by Rodeoclash** [comment]
@taion Thanks for this, it's working pretty well. Can't figure out how to get the environment / relay object on the props but I'm sure it's something I'm missing and explained somewhere in the example app 😄

**Comment by taion** [comment]
It's the same as if you're just using `<QueryRenderer>`s. Use like `context.relay.environment` or whatever.

**Comment by rosskevin** [comment]
@Rodeoclash here's a migration playbook to get to `modern`:
https://www.graph.cool/docs/tutorials/migrating-to-relay-modern-eijooto4se/

**Comment by Rodeoclash** [comment]
Yeah, it was a silly mistake. `createFragmentContainer` will inject the `relay` object into the props. I was trying to access it through a component mounted by the router (which only has a fragment).

Either way, I construct the environment in a seperate module so can easily import into whatever component needs to do a mutation.

@rosskevin Thanks for the link
