### ISSUE TITLE
Duplicate queries?

### ISSUE THREAD

**Issue by cellis** [4Catalyzer/found-relay#120]
Hello again! I'm using this with relay and postgraphql. What I'm wondering is why I get multiple queries for `currentUser`. Below is my router:

```javascript
const routes = makeRouteConfig(
    <Route
      path='/'
      Component={Layout}
      query={
        graphql`
          query router_Layout_Query {
            currentUser {
              lastName
            }
          }
        `
      }
    >
      <Route
        getComponent={() =>
          System.import('../components/SignUp').then(
            module => module.default
          )}
        render={LoadingComponent}
      />
      <AuthorizedRoute
        path='profile'
        getComponent={() =>
          System.import('../components/Profile').then(
            module => module.default
          )}
        query={
          graphql`
            query router_Profile_Query {
              currentUser {
                ...Profile_currentUser
              }
            }
          `
        }
      />
    </Route>
  );
```

And Profile.js has:

```
export default createFragmentContainer(
  Profile,
  {
    currentUser: graphql`
      fragment Profile_currentUser on User {
        lastName
      }
    `,
  }
);
```

But when I load the page, I get the following requests in the server:

```bash
0 error(s) as postgraphql_user in 360.9ms :: query router_Layout_Query { currentUser { lastName id } }

0 error(s) as postgraphql_user in 355.74ms :: query router_Profile_Query { currentUser { ...Profile_currentUser id } } fragment Profile_currentUser on User { lastName }
```

And sure enough there are duplicated entries for `currentUser`: 

```html

            window.__RELAY_PAYLOADS__ = [{"data":{"currentUser":{"lastName":"Mills","id":"WyJ1c2VycyIsMzdd"}}},{"data":{"currentUser":{"lastName":"Mills","id":"WyJ1c2VycyIsMzdd"}}}];
```
I must be doing something wrong, but what?

**Comment by taion** [comment]
That's expected.

We have no ability to merge queries here – in Relay, all the queries are fully static (to work w/things like persisted queries), and we have to pass them through as-is.

In general, it's best to use a batching network layer, plus something like `DataLoader` in the GraphQL server.

**Comment by cellis** [comment]
@taion thanks a lot. I'm looking into using https://github.com/nodkz/react-relay-network-modern, as the Network layer. I looks like it merges / batches.

**Comment by taion** [comment]
Sure, or Apollo Link might work too.

**Comment by cellis** [comment]
@taion So I've been researching this quite a bit. It looks like most of these batching / caching libraries will only help with truly duplicate queries, i.e. queries with the same signature. Thus: 
```javascript
//query 1
graphql`query router_Layout_Query { currentUser { lastName id } }`
```
is different from 
```javascript
//query 2
graphql`query router_Profile_Query { currentUser { ...Profile_currentUser id } } fragment Profile_currentUser` on User { lastName }
```
Even though they have the same semantics.

What I want is, when query 1 is executed, for query 2 to be read from network cache if possible. And if not, read from the graphql server. Instead, using any of the above caches ( QueryResponseCache ) etc, it seems they will not break out an AST and start diffing. Which means that using `found-relay` will cause new queries for every sub route. Of course you could just optimize your graphql server to be more performant but it would be nice if there was a clean way ( using your FetcherBase ) class, to simply diff queries against a cache before execution. Am I making any sense here?

**Comment by taion** [comment]
As you noted, if you want to implement this, it's something you could add to your own network layer.

As far as I'm aware, Relay Modern doesn't do any sort of AST diffing like this out-of-the-box in any case. The goal of this library is to set up the integration such that behavior matches what would happen if each route were its own `<QueryRenderer>`.

The intention here is exactly that each route sends its query independently – it's just that they get sent in parallel without waterfalls in the case of nested routes, and they get executed in conjunction with loading split-out code bundles.
