### ISSUE TITLE
Warning: Failed context type: Invalid prop/context `relay` supplied to `Component`, expected `undefined` to be an object with a classic `environment` implementation and `variables`.     in Relay(TodoApp)     in ElementsRenderer     in StaticContainer     in RouterProvider     in Provider

### ISSUE THREAD

**Issue by dsdharam91** [4Catalyzer/found-relay#126]
### Adding SSR support to relay classic example https://github.com/4Catalyzer/found-relay/tree/master/examples/todomvc-classic
import express from 'express';
import { getFarceResult } from 'found/lib/server';
import queryMiddleware from 'farce/lib/queryMiddleware';
import { Resolver } from 'found-relay';
import { RelayNetworkLayer, urlMiddleware } from 'react-relay-network-layer';
import createRender from 'found/lib/createRender';
import 'fetch-everywhere';
import toGraphQL from 'react-relay/lib/toGraphQL';
import ReactDOMServer from 'react-dom/server';
import serialize from 'serialize-javascript';
import Relay from 'react-relay/classic';
import path from 'path';
import render from './src/render';
import routeConfig from './src/routeConfig';
import webpack from 'webpack';
import WebpackDevServer from 'webpack-dev-server';
import webpackMiddleware from 'webpack-dev-middleware';
import RelayLocalSchema from 'relay-local-schema/lib/classic';
import schema from './src/data/schema';
Relay.injectNetworkLayer(new RelayLocalSchema.NetworkLayer({ schema }));
// Serve the Relay app
const PORT = 3000;
const app = express();

const webpackConfig = {
  entry: ['babel-polyfill', './src/client'],

  output: {
    path: path.resolve(__dirname, 'build'),
    filename: 'bundle.js',
  },

  module: {
    rules: [
      { test: /\.js$/, exclude: /node_modules/, use: 'babel-loader' },
      { test: /\.css$/, use: ['style-loader', 'css-loader'] },
      { test: /learn\.json$/, use: 'file-loader?name=[name].[ext]' },
    ],
  },
};

app.use(
  webpackMiddleware(webpack(webpackConfig), {
    publicPath: webpackConfig.output.publicPath,
    stats: { colors: true },
  }),
);

app.use(async (req, res) => {
  const { redirect, status, element } = await getFarceResult({
    url: req.url,
    historyMiddlewares: [queryMiddleware],
    routeConfig,
    resolver: new Resolver(Relay.Store),
    render
  });

  if (redirect) {
    res.redirect(302, redirect.url);
    return;
  }

  res.status(status).send(`
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Found Universal Example</title>
</head>
<body>
<div id="root">${ReactDOMServer.renderToString(element)}</div>
<script src="bundle.js"></script>
</body>
</html>
  `);
});

app.listen(PORT, () => {
  console.log(`listening on port ${PORT}`); // eslint-disable-line no-console
});

**Comment by taion** [comment]
You definitely don’t want to be using the singleton `Relay.Store` if you’re doing SSR. Otherwise just follow the error message – you’re passing in `undefined` in place of a Relay environment.
