### ISSUE TITLE
Dynamic query prop

### ISSUE THREAD

**Issue by noone0012** [4Catalyzer/found-relay#127]
Hi there!
There's one little issue with query prop. I'm hoping you can help to solve this.

I've got two routes on the same path '/' . "Register" and already logged in app "Newsfeed".
How can I dynamically render these two pages and send query when only user is logged in.
I've tried in many ways but it's no use.

https://prnt.sc/inb5ya
route always sends request since route is activated. And also says `
http://prntscr.com/inbfgq
but in the component I still have access to that prop.

**Comment by taion** [comment]
Use `getQuery` instead of `query`. This callback can return whatever query you want.
