### ISSUE TITLE
Preserving scroll position on navigating back

### ISSUE THREAD

**Issue by mbaquerizo** [4Catalyzer/found-relay#128]
Sorry in advance if this question doesn't belong here.

I have a search results page that renders a list of results with a `<Link />` to the details page for each result. I want to be able to navigate back to the search results in the same scroll position I was in when clicking the link to the details page. I have seen some mention of scroll position on the `farce` documentation `StateStorage` section but seeing an example of how I can implement this or another strategy would be helpful.

I can provide any more information if needed.
Thanks

**Comment by taion** [comment]
Use Found Scroll: https://github.com/4Catalyzer/found-scroll
