### ISSUE TITLE
Named components

### ISSUE THREAD

**Issue by alexhawkins** [4Catalyzer/found-relay#34]
@taion I've converted a huge app from react-router-relay to found-relay and relay modern as you suggested. It works for the most part except for where I used named components. I made heavy use of named components in my relay classic app but have not been able to figure out how to do it with relay modern using found-relay. Any help would be much appreciated.

**Comment by taion** [comment]
See https://github.com/4Catalyzer/found/issues/55 and https://github.com/4Catalyzer/found/pull/67. It's coming soon.
