### ISSUE TITLE
Redux and found-relay

### ISSUE THREAD

**Issue by kathleenchen33** [4Catalyzer/found-relay#35]
Hi, 

I was wondering if they are any known issues with using found-relay and redux. When I do

<img width="435" alt="screen shot 2017-06-16 at 12 43 53 pm" src="https://user-images.githubusercontent.com/29487958/27236121-93e540a6-5291-11e7-9ed2-1da5a6e3f6b8.png">

I essentially can not use redux. When I fire actions nothing happens. 

But when I replace `<Router resolver={new Resolver(environment)} />` with `<App />` essentially removing the router - I can fire the actions again. Are their any conflicts with store in router and redux? thanks.

**Comment by taion** [comment]
You must follow https://github.com/4Catalyzer/found#createconnectedrouter if you are using your own Redux store and provider.
