### ISSUE TITLE
Parent Route jsx without render/component - Relay routes without a render method must specify a component.

### ISSUE THREAD

**Issue by rosskevin** [4Catalyzer/found-relay#37]
I'm trying to get running after a conversion to modern, and bumped into https://github.com/4Catalyzer/found-relay/blob/next/src/modern/ReadyStateRenderer.js#L85:

`Relay routes without a render method must specify a component.`

Here is a sample:
```js
  <Route path='/samples'>
    <Route path='layout' getComponent={() => import('./Grid').then(module => module.default)} />
    <Route path='text' getComponent={() => import('./Text').then(module => module.default)} />
  </Route>
```

Is a parent Route jsx not supported as it was with react-router/react-relay-router or am I just missing something?  It seems this is ok with `found`, but not with `found-relay`?

**Comment by taion** [comment]
Err there aren't queries on any of those routes? Also worth making sure that neither of those are evaluating as undefined/null.

**Comment by rosskevin** [comment]
This is just a sandbox for widgets we use in dev, and absolutely no queries there.

**Comment by rosskevin** [comment]
Another sample with our authentication routes jsx, we use a dummy `<Route/>` wrapper, is there another way to do this and still use jsx?

```js
  routes (): Object {
    return (
      <Route>
        <Route path='signout' render={this.renderSignout} />
        <Route path='signin' render={this.renderRedirectToDashboard} />
        <Route
          path='signup'
          getComponent={() => import('../../Authentication/SignUpPage').then(module => module.default)}
          render={this.renderRedirectToDashboard}
          undock
        />
        <Route
          path='resetPassword'
          getComponent={() => import('../../Authentication/ResetPasswordPage').then(module => module.default)}
          render={this.renderResetPasswordEnsureSignedOut}
        />
        <Route
          path='changePassword'
          getComponent={() => import('../../Authentication/ChangePasswordPage').then(module => module.default)}
          render={this.renderInauthenticRedirectToRoot}
        />
      </Route>
    )
  }
```

**Comment by taion** [comment]
Something is weird here. If there's no `query`, we shouldn't be rendering a `<ReadyStateRenderer>` at all.

**Comment by taion** [comment]
See e.g. https://github.com/4Catalyzer/found-relay/blob/70145f23c7696f62a521e095873bd5aa4c7d158c/src/modern/Resolver.js#L137 – are we somehow incorrectly making a `querySubscription` there?

**Comment by rosskevin** [comment]
Debug looks good as far as resolution of routes.

![action_controller__exception_caught_and__2__parent_route_jsx_without_render_component_-_relay_routes_without_a_render_method_must_specify_a_component__ _issue__37_ _4catalyzer_found-relay](https://user-images.githubusercontent.com/136564/27404761-d6f991c4-5694-11e7-9b6c-4ba3b8e11257.png)

I'm looking at your comment/debugging regarding `querySubscription` now.

**Comment by rosskevin** [comment]
It's failing here on this wrapper Route:

```js
import Route from 'found/lib/Route'
import React from 'react'
import {RouteConfig} from '../../config'

export default class extends RouteConfig {
  routes (): Object {
    return (
      <Route path='/'>
        <Route
          getComponent={() => import('./LandingPage').then(module => module.default)}
          marketing
        />
        <Route render={this.renderAuthenticate}>
          <Route
            path='dashboard'
            getComponent={() => import('./DashboardPage').then(module => module.default)}
          />
        </Route>
      </Route>
    )
  }
}
```
`querySubscription` is null.  Still debugging, but looks as I would expect.

![action_controller__exception_caught](https://user-images.githubusercontent.com/136564/27405206-45d36826-5696-11e7-993b-ce0976aa2666.png)

**Comment by rosskevin** [comment]
These routes actually looked collapsed and appropriate.  I'm going to try to dump the consolidated routes from `makeRouteConfig` to get a bigger picture.

**Comment by taion** [comment]
I'd just drop a breakpoint there and see how it's even getting to that `return` with the `<ReadyStateRenderer>`.

**Comment by rosskevin** [comment]
@bmcdaniel11 found it, it was a lowercase `c` on `Component`.  Is that something you want to check and complain about since it might be a common migration error from old react-router?

**Comment by taion** [comment]
https://github.com/4Catalyzer/found/issues/105

**Comment by taion** [comment]
Not a fix – just an issue tracking it in the right place.
