### ISSUE TITLE
Q: resetting relay environment + forceUpdate unmount/remounts

### ISSUE THREAD

**Issue by rosskevin** [4Catalyzer/found-relay#42]
Regarding: https://github.com/facebook/relay/issues/233#issuecomment-284586190

We had this working well with older relay and react-router-relay.  This worked as creating a new environment on auth change, and running `forceUpdate()`.

Now that we have switched to relay 1.1 and found-relay, while this same method works, it is unMounting/reMounting our top level root route component called `AppFrame`.  This is causing a problem because our `NotificationCenter` is rendered within `AppFrame`, and the unmounted `NotificationCenter` receives the auth change message (e.g. `Signed out`) before the new one is mounted, so our auth user notifications are disappearing.

I tried killing the `forceUpdate` which no longer unmounts `AppFrame`, but the problem is that `AppFrame` is still rendering with the _old_ relay enviroment.

Routes:

```js
    return (
      <Route
        Component={AppFrame}
        query={graphql`
          query appRoutes_DummyApp_Query {
            currentUser {
              ...AppFrame_currentUser
            }
          }`
        }
      >
        {this.resolve(AuthenticationRoutes)}
        {this.resolve(HomeRoutes)}
        {this.resolve(SamplesRoutes)}
        {this.resolve(OrganizationRoutes)}
        {this.resolve(ContactRoutes)}
      </Route>
    )
```

Here is our reset:

```javascript
// @flow

import {Environment, Network, RecordSource, Store} from 'relay-runtime'
import {JSON_META} from '../util/Fetch/Fetch'
import Logger from '../util/Logger'

const log = Logger.get('CurrentRelay')

/**
 * Define a function that fetches the results of an operation (query/mutation/etc)
 *
 * @param operation
 * @param variables
 * @param cacheConfig
 * @param uploadables
 * @returns Promise
 */
function fetchQuery (
  operation,
  variables,
  cacheConfig,    // eslint-disable-line no-unused-vars
  uploadables     // eslint-disable-line no-unused-vars
) {
  return fetch('/graphql', {
    ...JSON_META,
    method: 'POST',
    body: JSON.stringify({
      query: operation.text, // GraphQL text from input
      variables
    })
  }).then(response => {
    return response.json()
  })
}

// https://github.com/facebook/relay/issues/233 shows how to reset Relay Store using Relay.Environment
class CurrentRelay {
  environment: null

  constructor () {
    this.reset()
  }

  reset () {
    this.environment = new Environment({
      network: Network.create(fetchQuery),
      store: new Store(new RecordSource())
    })
    log.debug('reset completed for Relay environment')
  }
}

const currentRelay = new CurrentRelay()
export default currentRelay
```

And in our App:

```js
  onAuthChange = () => {
    // need to reset our Relay.Store on auth change to clear the cache
    currentRelay.reset()
    this.forceUpdate()
  }
```

While I can work around this in some kind of global notification queue or delay,  I first want to stop and ask if this is the prefered way of handling such thing.  

Is there a better way to make `AppFrame` aware of the new environment after reset?

**Comment by taion** [comment]
Try defining a `render` method on your `AppFrame` route that will render the `AppFrame` even when the data aren't available (or else have some sort of static-container-y thing to keep rendering with the previous props).

The issue is that when you recycle the environment, we need to re-fetch the root query as well, so we need to render _something_ in that place while this is happening.

I guess I should figure out how to support something like the root "global pending" example here. Let me know if this works for you.

**Comment by rosskevin** [comment]
Thanks @taion, this created similar behavior as before:


```js
let cachedComponent

return (
  <Route
    Component={AppFrame}
    query={graphql`
          query appRoutes_DummyApp_Query {
            currentUser {
              ...AppFrame_currentUser
            }
          }`
    }
    render={({ Component, props }) => {
      if (Component && props) {
        cachedComponent = <Component {...props} />
        return cachedComponent
      } else if (cachedComponent && props === null) {
        return cachedComponent
      } else {
        return (<div>
          <small>Loading</small>
        </div>)
      }
    }}
  >
    {this.resolve(AuthenticationRoutes)}
    {this.resolve(HomeRoutes)}
    {this.resolve(SamplesRoutes)}
    {this.resolve(OrganizationRoutes)}
    {this.resolve(ContactRoutes)}
  </Route>
)
```

**Comment by taion** [comment]
Okay. Worth keeping an eye on https://github.com/4Catalyzer/found-relay/issues/43, BTW, which will add something similar as default behavior.

**Comment by taion** [comment]
I would use `<StaticContainer shouldUpdate={!!props}>`, BTW.

**Comment by rosskevin** [comment]
@taion - referring to https://github.com/reactjs/react-static-container ?

**Comment by taion** [comment]
Yes.
