### ISSUE TITLE
Allow hitting global renderPending

### ISSUE THREAD

**Issue by taion** [4Catalyzer/found-relay#43]
We should support `render` methods returning `undefined`, which will then cause things to hit the global `renderPending`, as in base Found.

This should be the default when specifying only `Component` and no `render`.

This might require/work best with removing `prerender` and just passing in an `initialRender` property to `render` to signify initial renders (when throwing Found errors would be allowed).

**Comment by taion** [comment]
This would accomplish something similar to #29.

**Comment by malcolmwhite** [comment]
Thanks for the quick response!

**Comment by taion** [comment]
Depends on #45
