### ISSUE TITLE
How do you route to a specific item?

### ISSUE THREAD

**Issue by dgroch** [4Catalyzer/found-relay#49]
I'm very new to GraphQL and Relay. I hit a wall today trying to figure out how to route to a single item, ie can't figure out how to pass the a route param into graphql query. 

For example say I have a route /products/1 and I pluck this idea from location props. How do I pass this in as an argument in the query fragment?

Eg node(id: productId) {
  title
  price 
  etc
}

**Comment by taion** [comment]
See https://github.com/4Catalyzer/found-relay/blob/a439517ecea41231e7fc1f9d4b54ae6e45b32e0f/test/modern/Resolver.test.js#L102-L126.
