### ISSUE TITLE
Just one example

### ISSUE THREAD

**Issue by ohardy** [4Catalyzer/found-relay#5]
Hi,

Just one example to use it can be very useful :)

Thanks in advance

**Comment by taion** [comment]
see the examples dir

**Comment by ohardy** [comment]
No examples dir in this repo, only one in `found` ;)

**Comment by taion** [comment]
oh i see

**Comment by ekosz** [comment]
I'm really interested in `found` as well as its integration with Relay. And example on how to use `found-relay` would be awesome.

**Comment by taion** [comment]
Take a look at https://github.com/taion/relay-todomvc/tree/found.

I don't have a more detailed example yet, but this demonstrates basic usage.

**Comment by taion** [comment]
See specifically https://github.com/taion/relay-todomvc/blob/989ca08f364303f38c29fd27f8fedf82f05ea41a/src/client.js#L38 and https://github.com/taion/relay-todomvc/blob/989ca08f364303f38c29fd27f8fedf82f05ea41a/src/routes.js, and check the diff for changes v. RRv2 and react-router-relay.

**Comment by taion** [comment]
Closing this for now since we have that example, more or less.

I'm also adding test coverage that should illustrate more advanced use cases anyway.
