### ISSUE TITLE
Retry does nothing because fetchPromise is not falsey

### ISSUE THREAD

**Issue by 0xCMP** [4Catalyzer/found-relay#53]
I have an issue I don't understand with my current Relay app using found-relay.

This line: https://github.com/4Catalyzer/found-relay/blob/e9f5fe225b33a2bb122d5ea38328c93d5f242f41/src/modern/QuerySubscription.js#L29

I have debugged and seen that while I have no requests in flight, a resolved promise is there and so it doesn't not do a proper check and refuses to make a request when I click a button I've wired up to do a retry.

# Steps to reproduce
You need:
- A relay application with a query on the route
- Two different routes

1. I loaded my React app and navigated to a route successfully.
1. I then disabled my internet via the Network tab of chrome
1. I navigated to another route with a query and it failed
1. I then clicked on a button which executes the `retry()` function given to the render function of the route.

edit: Sorry early post. Updated with rest of issue

**Comment by taion** [comment]
Thanks for the bug report. That's a regression introduced in a refactoring.

**Comment by rojobuffalo** [comment]
@0xCMP just curious, what retry function where you passing to render and how were you passing it? I was using the retry function in `react-router-relay` but don't see it documented in `found-relay`.

**Comment by taion** [comment]
It's the same as on QueryRenderer. It's a bug I accidentally introduced in alpha 2. I'll get a fix out this week.

**Comment by taion** [comment]
Fixed in [v0.3.0-alpha.5](https://github.com/4Catalyzer/found-relay/releases/tag/v0.3.0-alpha.5).
