### ISSUE TITLE
Isomorphic example

### ISSUE THREAD

**Issue by rojobuffalo** [4Catalyzer/found-relay#57]
Hey,

I was just trying to integrate this package with universal-webpack. I don't know if it's a bug or config error or if what I'm trying to do is unsupported. 

The question and code is all here:
https://stackoverflow.com/questions/45246891/getting-found-relay-to-work-with-universal-webpack

The error showing up when a page gets requested from the browser is `Cannot read property pathname of undefined`. And it's getting thrown from this call:

```
ReactDOMServer.renderToString(element)
```

**Comment by rojobuffalo** [comment]
Got some better logging and found that `createResolver(fetcher)` is returning an object with:

```
lastQueries: [ undefined, undefined ],
```

**Comment by rojobuffalo** [comment]
More logging

#### `/src/modern/Resolver`

```
...
async * resolveElements(match) {
    console.log('MATCH', match);
...
```

Output:

```
MATCH { location: { action: 'POP', pathname: '/', search: '', hash: '', query: {} },
  routeIndices: [ 0, 0 ],
  routeParams: [ {}, {} ],
  params: {},
  routes:
   [ Route { path: '/', Component: [Object], children: [Object] },
     Route { Component: [Function: HomePage] } ],
  match:
   { location: { action: 'POP', pathname: '/', search: '', hash: '', query: {} },
     routeIndices: [ 0, 0 ],
     routeParams: [ {}, {} ],
     params: {} },
  router:
   { push: [Function],
     replace: [Function],
     go: [Function],
     createHref: [Function],
     createLocation: [Function],
     addTransitionHook: [Function: addHook],
     matcher: Matcher { routeConfig: [Object] },
     isActive: [Function: isActive] },
  context: undefined }
```

**Comment by taion** [comment]
1. Are the fetch requests actually succeeding on the server?
2. Does this work if you don't use SSR? That `pathname` thing seems unrelated to anything you might be donig with SSR.

**Comment by rojobuffalo** [comment]
1. I'm not sure when the first API server request even happens. It looks like the Fetcher constructors don't call to the server. But I'm digging to see.
2. I got completely stuck on importing CSS where babel just wasn't handling it for server side compilation (which I think is different than rendering). It looked like the only option was to use something like universal-webpack or a css module hook, but the later wouldn't take care of images. So I'm having to take the big bite instead of building up to it.

**Comment by rojobuffalo** [comment]
`const relayPayloads = serialize(fetcher, { isJSON: true });`

Is returning an empty array in `server.js`. Is that unexpected?

**Comment by rojobuffalo** [comment]
My instinct is that the problem is around the last line of output seen in https://github.com/4Catalyzer/found-relay/issues/57#issuecomment-317135545. I say that because context is undefined, and it seems like somewhere there might be an expression like `context.location.pathname`.

**Comment by rojobuffalo** [comment]
I finally pinned down the expression that is generating the error:

https://github.com/4Catalyzer/found/blob/68ae966a079a75dbb09c49231a68673f1ec5bbf1/src/Matcher.js#L58

**Comment by rojobuffalo** [comment]
Well f* me. I had legacy code from when I was using `react-relay-router`. There was a component that was using `context.router.isActive`, which was getting through and failing inside `found`. 🤦
