### ISSUE TITLE
Garbage collection starts too early when using react-static-container in the render function

### ISSUE THREAD

**Issue by hannesj** [4Catalyzer/found-relay#62]
When using react-static-container in the render function as discussed #42 there is an issue when updating variables. It seems that ReadyStateRenderer calls this.selectionReference.dispose() too early. After the data has been downloaded, the subscriptions for fragment containers located inside the static container which is blocking updates from above it in the render tree, are updated for the old variables by calling setState directly for the individual fragment containers. At this point the data for the old variables has already been removed leaving undefined as values for the fields that use the variable as an argument.

**Comment by taion** [comment]
There's not really a great way to seamlessly handle this, because there's not really any way to know whether the rendered elements are getting captured.

I think the best approach might be to pass down either the `querySubscription` or the `operation` and let the user-supplied component use its own semantic knowledge about unmount lifecycles to do the retain/dispose.

What do you think?

**Comment by taion** [comment]
Maybe another way to think about this is – how would you solve this with just `<QueryRenderer>`? Or is that even possible?

**Comment by taion** [comment]
Another way to handle this that should work is to split out your routes, such that the `<ReadyStateRenderer>` with the data lives inside the `<StaticContainer>` (probably requires #48).

The other option is that, once I sort out https://github.com/4Catalyzer/found-relay/pull/45, you'd be able to return `undefined` from `render`, to hit a global `renderPending` method, which can render a `<StaticContainer>` in the same way.

**Comment by hannesj** [comment]
If I understand correctly, it seems that in QueryRenderer, the `selectionReference.dispose()` is called only after new data has been fetched in [onNext](https://github.com/facebook/relay/blob/master/packages/react-relay/modern/ReactRelayQueryRenderer.js#L235), rather than immediately when subscribing to a new query.

> The other option is that, once I sort out #45, you'd be able to return undefined from render, to hit a global renderPending method, which can render a <StaticContainer> in the same way.

How would this differ from the current situation with a `<StaticContainer>` in the render function?

**Comment by taion** [comment]
`ReadyStateRenderer` also calls `querySubscription.retain()`, though, so the ref count will be >0 as long as the `ReadyStateRenderer` remains mounted.

**Comment by taion** [comment]
Anyway, does that make sense? Put the `<StaticContainer>` _above_ the route for which you need to retain data.

**Comment by taion** [comment]
Going to close this out for now since it's been a while.
