### ISSUE TITLE
How to reset Relay environment

### ISSUE THREAD

**Issue by donut** [4Catalyzer/found-relay#64]
I have a mutation that needs to reset the Relay environment. The suggested solution is to use `new Relay.Environment()` to create a new environment instead of manually working through the store. But I don't see how I could hand off the new environment to found.

More details in [my StackOverflow question][soQuestion].

[soQuestion]: https://stackoverflow.com/questions/45361822/how-to-invalidate-relays-cache-after-mutation/45362658

**Comment by taion** [comment]
Wrap your router in another component that will create a new resolver when the environment changes, then pass that into the router.

**Comment by donut** [comment]
Thanks, again!
