### ISSUE TITLE
Router history

### ISSUE THREAD

**Issue by ericsin112** [4Catalyzer/found-relay#72]
@taion Hi taion, how can I listen the URL change? In relay-classic + react-router, I can get use `history.listen` method to listen the changes in child component. How can I do the same things now?

**Comment by taion** [comment]
Use a custom Redux store per https://github.com/4Catalyzer/found#createconnectedrouter, then attach listeners or reducers or whatever.

If you need to wait until all the data fetching is complete, you can also use a custom resolver, like https://github.com/4Catalyzer/found-relay/blob/2f8baee8496afbb78708fe271f753135bbac9fa4/test/modern/helpers.js#L40-L49.

**Comment by ericsin112** [comment]
As I'm using SSR, I need to use `createFarceRouter`. Is there any way to listen changes with `createFarceRouter`?

**Comment by taion** [comment]
They're not mutually exclusive. `createConnectedRouter` is a lower-level API than `createFarceRouter`.

**Comment by ericsin112** [comment]
Sorry, Would you please give me some example to using `createConnectedRouter `with `createFarceRouter`

**Comment by taion** [comment]
Again, see the docs I linked above: https://github.com/4Catalyzer/found#createconnectedrouter

It's basically the same. You just need to set up the Redux store yourself.

**Comment by ericsin112** [comment]
Ok. I will try it. Thanks for your help.
