### ISSUE TITLE
[Relay Modern] Can't pass new environment/resolver to router

### ISSUE THREAD

**Issue by Togrias** [4Catalyzer/found-relay#74]
We're trying to implement a resettable store and having issues passing a new Resolver to the router.
The code below is for a wrapper component around a Router that on reset() creates new source, store, network, environment and resolver instances. 

But once setState() is executed, the newly-instantiated objects immediately revert back to their old values. We're pretty flummoxed by this behaviour.

    reset = () => {
        const source = new RecordSource();
        const store = new Store(source);
        console.log(store); 
        const network = Network.create(this.props.fetchQuery);
        const environment = new Environment({store, network});
        const resolver = new Resolver(environment);
        this.setState({resolver});
    };
    
    render() {
        const Router = this.router;
        return <Router resolver={this.state.resolver}/>;
    }

I'm grateful for any help on this.

**Comment by taion** [comment]
Can you clarify what you mean by "revert back"? Does it render once with updated values, then immediately re-render with the old values?

**Comment by Togrias** [comment]
@taion I mean if you check out the code above, console.log(store) should log out a brand new object with no stored relay query results.

However, I instead keep getting my old store object, as if the reset never occurred.

Somehow, passing the new Resolver to the Router causes this issue. If I don't pass the new Resolver to the Router, console.log(store) logs out a new empty Store object. But of course, the reset() code is now unusable.

**Comment by taion** [comment]
I don't understand though. You're logging out the newly created store before you pass it into the router. Is it possible that one of those values (e.g. `Store`) is not what you think it is?

**Comment by taion** [comment]
See https://github.com/4Catalyzer/found-relay/pull/75. This seems to work fine.
