### ISSUE TITLE
TypeError: Cannot read property 'Container' of undefined

### ISSUE THREAD

**Issue by malofan** [4Catalyzer/found-relay#76]
Hello!
I'm getting this error every time whatever I do

```
TypeError: Cannot read property 'Container' of undefined
./node_modules/found-relay/lib/RelayRouteRenderer.js
node_modules/found-relay/lib/RelayRouteRenderer.js:45
  42 |     render: _propTypes2.default.func
  43 |   }).isRequired
  44 | }).isRequired,
> 45 | Component: _reactRelay2.default.PropTypes.Container,
  46 | environment: _reactRelay2.default.PropTypes.Environment,
```

May be I'm way too much tired but i can't figure out why do i even get it

Thank you for help!

**Comment by taion** [comment]
You're trying to use v0.2.x with Relay v1.x, which is not a valid combination, as flagged by peer dependencies. Use v0.3.x if you're using Relay v1.x.

**Comment by malofan** [comment]
Yeah, sorry. Just found it myself
