### ISSUE TITLE
All query being passed to a container

### ISSUE THREAD

**Issue by OskarKaminski** [4Catalyzer/found-relay#80]
Let's consider a route:
```
<Route
        path="table"
        Component={Table}
        prepareVariables={params => ({tableId: '59abf1a01710ba3b74718220'})}
        query={tableQuery} 
/>
```
With a query:
```
graphql`
query routesTableQuery($tableId: String){
    store {
        table(id: $tableId){
            ...Table_table
        }
    }
}`
```
And container with a fragment:
```
export default createFragmentContainer(
    Table,
    graphql`
        fragment Table_table on Table {
            name
            stake
        }
    `
)
```

Then the Table component receives store object instead of only table.
This violates the scope separation principle.
How can I pass down only the required fragment of data?

**Comment by taion** [comment]
Use a `render` function. The top-level container is analogous to the old-style `RootRenderer` containers and essentially are there just for convenience.
