### ISSUE TITLE
Error handling (HttpError and RedirectException) not working

### ISSUE THREAD

**Issue by jkettmann** [4Catalyzer/found-relay#83]
First of all thanks for this great library. I enjoy working with it a lot. I just came across a problem:

I want to display a 404 page when a `aNeccessaryProp` is not set. So I tried throwing a `HttpError` when `props` are set but  `aNeccessaryProp` is not set:

```
const routeConfig = {
  Component: MyComponent,
  query,
  render: ({ props }) => {
    if (props && props.aNeccessaryProp) {
      return <MyComponent {...props} />;
    } else if (!props.aNeccessaryProp) {
      throw new HttpError(404);
    }
    return null;
  }
};

<Route {...routeConfig} />
```
I thought, that handling the error in the `renderError` method supplied to `createRender` should be possible.
```
const render = createRender({
  renderError: ({ error }) => { // eslint-disable-line react/prop-types
    console.log('createRender error', error);
    switch (error.status) {
      case 404: return <div>404</div>;
      case 401: return <div>401</div>;
      default: return null;
    }
  },
});
```
But unfortunately the error is not caught: `asyncToGenerator.js:20 Uncaught (in promise) RedirectException {location: "/"}`

Throwing a `RedirectExpection` like `throw new RedirectExpection({ path: '/' })` also results in an uncaught error. 

So my question is: Is there something I'm doing wrong? How do you handle `HttpError`s and `RedirectException`s?

**Comment by jkettmann** [comment]
@taion Sorry, actually wanted to open this issue in Found after trying the examples there and also having no luck. Should we move it there?

**Comment by taion** [comment]
No, this is the right place. This is actually a quirk that (for Relay Modern) is fixed on `master` but not on the current release (alpha.6). On the current release you'd have to throw in `prerender` per https://github.com/4Catalyzer/found-relay/blob/v0.3.0-alpha.6/test/modern/prerender.test.js.

I didn't release my changes because I wanted to cut a v0.3.0 final with #60 (and maybe some docs), but I might as well cut a alpha.7 that lets you throw in `render` as opposed to having to use `prerender`.

**Comment by taion** [comment]
Released v0.3.0-alpha.7.

**Comment by jkettmann** [comment]
@taion Wow, that was quick. Thanks a lot

**Comment by taion** [comment]
The code was already there from a while ago, I just needed to cut the release :p

**Comment by jkettmann** [comment]
It tested the new release, and it works fine for a simple case. But I would like to check if a certain prop fetched by Relay is available and if not throw a 404. The problem now is that I cannot access all props queried by Relay.
```
const routeConfig = {
  Component: MyComponentContainer,
  query: graphql`
    query SomeQuery {
      someParent {
        ...MyComponentContainer_aNeccessaryFragment
      }
    }
  `,
  render: ({ props }) => {
    if (props && props.aNeccessaryProp) {
      return <MyComponentContainer {...props} />;
    } else if (props && !props.aNeccessaryProp) {
      throw new HttpError(404);
    }
    return null;
  }
};

<Route {...routeConfig} />
```
where looks like
```
MyComponentContainer_aNeccessaryFragment = graphql`
  aNeccessaryProp {
    ...
  }
`
```
In the props in render function I don't have access to `aNeccessaryProp`, `someParent` only contains `fragments`. When I `throw new HttpError(404)` inside `MyComponentContainer.render` the error is not caught.

So I'm a bit confused on what the right approach is with `Found`. Is this something I would handle client side or should I rather throw some error on the GraphQL server? I probably can't use the components render method for throwing these errors, but the Found related methods don't give me access to the needed props, right?

Thanks a lot for any help

**Comment by taion** [comment]
That's just how Relay works, actually. By default fragments are masked.

I would just encapsulate exactly the fields I need in the route query. It's the right kind of encapsulation anyway – dropping into a component fragment from the parent seems not great from an encapsulation POV.

You can also use unmasked fragments: https://facebook.github.io/relay/docs/relay-directives.html#relay-mask-boolean

**Comment by jkettmann** [comment]
@taion Thanks for your help. That was actually quite obvious, you're right. If anyone else has a similar problem: I just pulled `aNeccessaryProp` from the child into the parent.
```
query SomeQuery {
  someParent {
    aNeccessaryProp {
      ...MyComponentContainer_fragment
    }
  }
}
```
Now I can access `aNeccessaryProp` in the routes `render` function.
