### ISSUE TITLE
Handle graphql server error

### ISSUE THREAD

**Issue by ohardy** [4Catalyzer/found-relay#86]
renderError is never called when my GraphQL server return for example :

```
{"errors":[{"locations":[{"column":3,"line":5}],"message":"current transaction is aborted, commands ignored until end of transaction block\n"}],"data":{"category":null}}
```

How catch that and redirect the user to a specific page ?

**Comment by taion** [comment]
If you want to redirect, see https://github.com/4Catalyzer/found-relay/blob/master/test/modern/render.test.js#L132

If you're looking to render errors in general, see https://github.com/facebook/relay/issues/1913

`renderError` only gets called if you throw `HttpError` from `render`

**Comment by dminkovsky** [comment]
I'm not interested in redirect, but I am interested in seeing `errors` alongside `data` in my props.  

The current version of `<QueryRenderer>` [provides them](https://github.com/facebook/relay/blob/v1.4.1/docs/modern/QueryRenderer.md):

```
  render={({error, props}) => {
    if (error) {
      return <div>{error.message}</div>;
    } else if (props) {
      return <div>{props.page.name} is great!</div>;
    }
    return <div>Loading</div>;
  }}
``` 

I'm guessing at the time you posted facebook/relay#1913, that was not the case? Based on that thread, it looks like the [simplest workaround](https://github.com/facebook/relay/issues/1913#issuecomment-338987955) is:

```
if (result && result.errors) {
  return {data: null, errors: result.errors};
}
```

What do you suggest now, 7 months later?
