### ISSUE TITLE
component gets initialised with null prop if ID is not defined in graphql schema?

### ISSUE THREAD

**Issue by snkhubcom** [4Catalyzer/found-relay#94]
The issue Im having is that my query's get executed, and I see a response coming back from the server. But my component does not receive the data via the props. At runtime it throws the following warning:

createFragmentSpecResolver: Expected prop `streets` to be supplied to `Relay(SenderPage)`, but got `undefined`. Pass an explicit `null` if this is intentional.

The only difference I see from the example is that my schema does not specify IDs
so where the example has fragments like this: 

fragment TodoApp_viewer on User {
      id
      ...TodoListFooter_viewer
    }

my fragments are similar but there is no viewer object and it misses the id on top. Is this mandatory for it to work? Or am I doing something else wrong.

query AppFetchStreetQuery($countrycode:String!, $postalcode:String!) {
    ...ListPage_streets
}

**Comment by taion** [comment]
Once you're rendering, this library will have the same behavior as using a `<QueryRenderer>` in Relay normally. Most likely you are actually forgetting to pass down the prop or something.
