### ISSUE TITLE
How to make redirect from network layer?

### ISSUE THREAD

**Issue by CostaRico** [4Catalyzer/found-relay#95]
Here is my network layer:
```javascript
function fetchQuery(operation,
                    variables,
                    cacheConfig,
                    uploadables) {
	// return fetch('https://api.graph.cool/relay/v1/cj07pfjjj1nbq0148rutjhxd5', {
	return fetch('http://localhost:3010/graphql', {
		method: 'POST',
		headers: {
			'Accept': 'application/json',
			'Content-Type': 'application/json',
		},
		body: JSON.stringify({query: operation.text})
	}).then(response => {
		
		if(response.status == 401){
			throw new Error('Network response was not ok.');
// HOW TO MAKE REDIRECT TO LOGIN PAGE HERE?

		}
		

		return response.json();
	});
}
```

Help me please!

**Comment by taion** [comment]
You wouldn't do the redirect from the network layer. Instead add a route that e.g. throws a `RedirectException` in `render`, per https://github.com/4Catalyzer/found-relay/blob/2071b36c445475c367d6ecaf18cce1dfefafab46/test/modern/render.test.js#L144-L147.

**Comment by CostaRico** [comment]
@taion I've tried this way, but resolving is undefined always.
props are filled if there is no error
errors are undefined all the time

If error: 
![2017-10-09_22-37-40](https://user-images.githubusercontent.com/3001018/31355715-1378cfb0-ad44-11e7-896f-0ac9101aad31.png)

if data exist:
![2017-10-09_22-48-09](https://user-images.githubusercontent.com/3001018/31355751-3091ebd6-ad44-11e7-8e95-c31232b50e86.png)


May be something wrong with my network layer?

```javascript 

import fetch from 'isomorphic-fetch';
import {
  Environment,
  Network,
  RecordSource,
  Store
} from 'relay-runtime';

function fetchQuery(
  operation,
  variables,
  cacheConfig,
  uploadables
) {
  return fetch('https://api.graph.cool/relay/v1/cj07pfjjj1nbq0148rutjhxd5', {
    method: 'POST',
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({query: operation.text})
  }).then(response => {
    return response.json();
  }).then(data=>{
    debugger;
    return data;
  });
}

// Create a network layer from the fetch function
const network = Network.create(fetchQuery);
const source = new RecordSource();
const store = new Store(source);

export default new Environment({
  network,
  store
})

```

You can try it:
https://github.com/CostaRico/graphql-relay

yarn install
yarn relay
yarn dev

**Comment by taion** [comment]
Your lockfile has alpha 6. Upgrade to the latest alpha.

**Comment by CostaRico** [comment]
@taion if I switch to latest then I get error like here https://github.com/4Catalyzer/found-relay/issues/76
"Cannot read property 'Container' of undefined"

So if I get it right way, I need to switch to "react-relay": ">=0.6.0 <1.0.0", also. 
Is it mean I cant use relay modern in this case?

Thx u for your time!

**Comment by taion** [comment]
Not latest. Use `next`.

**Comment by peet86** [comment]
@taion: My question is really similar to the original one...   I would like to handle the error case when the graphql server is down.. I can catch the error in the network layer but I want to handle it somewhere in the rendering logic. But as I see non of the render method's arguments reflect the http error state.. 

I've tried to check for props ===  null but sometimes props has null value even when the graphql endpoint is up..  and as I see there is no other relevant/reliable argument to check...


GraphQL down: 
`{ error: null,
  props: null,
  retry: null,
  resolving: true }`

GraphQL up: 
`{ error: null,
  props: object or null, <-- ???
  retry: [func],
  resolving: true }`


@CostaRico: have you solved this at the end?

**Comment by CostaRico** [comment]
@peet86 I solved what I've asked originally thx to @taion 
But next I've tried to render error messages and it's too difficult.
Finally i've chosen to use redux for a while. 
When relay modern will be more mature I try again. :)

**Comment by taion** [comment]
@peet86 See https://github.com/facebook/relay/issues/1913. I'm just matching the semantics of `<QueryRenderer>` here. You'll want to explicitly throw in the network layer.

**Comment by CostaRico** [comment]
@taion it would be nice to have some examples
and thx u for all u do!

**Comment by taion** [comment]
It would be better for such examples to live upstream for facebook/relay. They're not specific to Found Relay.
