### ISSUE TITLE
Multiple query roots for a single route

### ISSUE THREAD

**Issue by cmutzel** [4Catalyzer/found-relay#97]
In react-router-relay I was able to create multiple query roots on a single route, i.e. a route could have a two queries like:
```
const RootQuery = {
  foo: graphql`
    query {
      node (idOfAFooNode: $Id)  {
        ...ComponentFragment_foo
      }
    }
   `,
  bar: graphql`
    query {
      node (id: $IdOfABarNode)  {
        ...ComponentFragment_bar
      }
    }
   `
};
```

This way my root component would have this.props.foo and this.props.bar. 

Is this possible in found-relay?  I've try to look through the examples for relay-modern + code and it  possible to create multiple query roots on a single route?  Maybe there is another way you folks have thought about a way to do this?

**Comment by taion** [comment]
Relay Modern queries don't have the same limitation of only having a single field at top-level, so you'd just use multiple roots in the same query.

**Comment by cmutzel** [comment]
Got it, thanks @taion
